# itk-version: 1.0.0
version: "3"

networks:
  app:
    driver: bridge
    internal: false

services:
  database:
    image: mariadb:10.6
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db

  nginx:
    image: webdevops/php-nginx:8.0-alpine
    networks:
      - app
    depends_on:
      - database
    ports:
      - '80'
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - .:/app:delegated

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - '1025'
      - '8025'
